---
- include: provision.yml
- include: installer/{{ installer.type }}/environment-setup/main.yml

- name: Run tripleosh on the host
  hosts: undercloud
  vars:
    tripleosh_git: https://github.com/sshnaidm/tripleo-ci.git
  environment:
    EPEL_MIRROR: http://dl.fedoraproject.org/pub/epel
    CENTOS_MIRROR: http://mirror.centos.org/centos
    FEDORA_MIRROR: http://dl.fedoraproject.org/pub/fedora/linux
    NODECOUNT: 2
    INTROSPECT: 1
    PACEMAKER: 0
    OVERCLOUD_DEPLOY_ARGS: "--libvirt-type=qemu"
    NETISO_V4: 1

  tasks:
    - name: clone tripleosh
      git: repo={{ tripleosh_git }} dest={{ instack_user_home }}/tripleo-ci force=yes

    - name: Run repo setup
      command: /usr/bin/bash {{ instack_user_home }}/tripleo-ci/scripts/tripleo.sh --repo-setup

    - name: Run undercloud setup
      command: /usr/bin/bash {{ instack_user_home }}/tripleo-ci/scripts/tripleo.sh --undercloud

    - name: Run building overcloud images
      command: /usr/bin/bash {{ instack_user_home }}/tripleo-ci/scripts/tripleo.sh --overcloud-images

    - name: Run nodes registering
      command: /usr/bin/bash {{ instack_user_home }}/tripleo-ci/scripts/tripleo.sh --register-nodes

    - name: Run nodes introspection
      command: /usr/bin/bash {{ instack_user_home }}/tripleo-ci/scripts/tripleo.sh --introspect-nodes

    - name: Run overcloud deployment
      command: /usr/bin/bash {{ instack_user_home }}/tripleo-ci/scripts/tripleo.sh --overcloud-deploy

    - name: Run overcloud deployment
      command: /usr/bin/bash {{ instack_user_home }}/tripleo-ci/scripts/tripleo.sh --tempest-run
      ignore_errors: yes

    - name: Fetch xml to host
      fetch: src={{ instack_user_home }}/tempest/tempest.xml dest={{ base_dir }}/khaleesi/nosetests.xml flat=yes
